version: '3.1'

services:
  web:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
<<<<<<< HEAD
=======
    networks:
      - authapi
>>>>>>> 6ccfcf3 (getting started with automated testing)

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./tests/database:/docker-entrypoint-initdb.d
    networks:
      - authapi

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - 5050:80
    depends_on:
      - postgresql
    networks:
      - authapi

networks:
  authapi:
    driver: bridge
