"""Add password to person table

Revision ID: 10e334fa8692
Revises: 6a4b319fae29
Create Date: 2024-05-20 19:35:26.276391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '10e334fa8692'
down_revision: Union[str, None] = '6a4b319fae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.String))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password')
    # ### end Alembic commands ###