"""add attemps on session table

Revision ID: 603c2c6e693c
Revises: fa30b735a332
Create Date: 2024-06-01 11:38:28.582890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603c2c6e693c'
down_revision: Union[str, None] = 'd134068d766d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('attemps', sa.Integer, nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'attemps')
    # ### end Alembic commands ###