"""Created person table

Revision ID: 6a4b319fae29
Revises: 
Create Date: 2024-05-20 19:32:06.300386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4b319fae29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'person',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('first_name', sa.String, index=True),
        sa.Column('last_name', sa.String, index=True),
        sa.Column('username', sa.String, unique=True, index=True),
        sa.Column('password', sa.String, index=True),
        sa.Column('birth_date', sa.Date),
        sa.Column('created_at', sa.DateTime, server_default=sa.text('NOW()')),
        sa.Column('last_login', sa.DateTime)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('person')
    # ### end Alembic commands ###