"""Remove last_login from Person and add Session model

Revision ID: 7659ce9f2f1a
Revises: 10e334fa8692
Create Date: 2024-05-21 22:17:11.811136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7659ce9f2f1a'
down_revision: Union[str, None] = '10e334fa8692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'last_login')
    op.create_table(
        'session',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('jwt_token', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('person_id', sa.INTEGER(), sa.ForeignKey('person.id'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.add_column('person', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###