"""Add end_session to session

Revision ID: bc5dde38adf6
Revises: d134068d766d
Create Date: 2024-05-21 22:50:48.496756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc5dde38adf6'
down_revision: Union[str, None] = 'd134068d766d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_index('ix_person_first_name', table_name='person')
    op.drop_index('ix_person_id', table_name='person')
    op.drop_index('ix_person_last_name', table_name='person')
    op.drop_index('ix_person_username', table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('person_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_person_username', 'person', ['username'], unique=True)
    op.create_index('ix_person_last_name', 'person', ['last_name'], unique=False)
    op.create_index('ix_person_id', 'person', ['id'], unique=False)
    op.create_index('ix_person_first_name', 'person', ['first_name'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jwt_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_session', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='session_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    # ### end Alembic commands ###
