"""Add end_session to session

Revision ID: d134068d766d
Revises: 7659ce9f2f1a
Create Date: 2024-05-21 22:34:11.184362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd134068d766d'
down_revision: Union[str, None] = '7659ce9f2f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('end_session', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'end_session')
    # ### end Alembic commands ###